=== Leidenschaft/Deutsch-Lernen/Wort/example/NounModel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Entry (Stichwort, Aussprache*, Einheit*, Anteil*,
Genus*, Pluralform*, GenitivSingular*, zusammengesetzteWörter,
Synonymegruppe,
Antonymegruppe,Kollokationen,AllgemeineErläuterungen,Comment?)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Aussprache (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT Genus (#PCDATA)>
<!ELEMENT Pluralform (#PCDATA)>
<!ELEMENT GenitivSingular (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_)*>
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ELEMENT Comment (#PCDATA)>
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>    
  <!ATTLIST K link CDATA #IMPLIED>    
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>
<!ATTLIST Stichwort link CDATA #IMPLIED>
<!ATTLIST Stichwort Band CDATA #IMPLIED>
<!ATTLIST Stichwort Bild CDATA #IMPLIED>
<!ATTLIST Stichwort Audio CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/163.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Unterricht</Stichwort>
  <Einheit>1</Einheit>
  <Anteil>Text</Anteil>
  <Genus>der</Genus>
  <Pluralform>nur Sg</Pluralform>
  <GenitivSingular>Unterricht(e)s</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <_K>Unterrichtsstunde</_K>
      <_K>Unterrichtsfach</_K>
      <_K>Unterrichtsgegenstand</_K>
      <_K>Unterrichtsmaterial</_K>
      <_K>Unterrichtsmethode</_K>
      <K_>Chemieunterricht</K_>
      <K_>Klavierunterricht</K_>
      <K_>Sportunterricht</K_>
    </KompositaCollection>
    <abgeleiteteWörter>
      <hierzu category="Verben">unterrichten</hierzu>
      <hierzu category="Adjektiv">unterrichtsfrei</hierzu>
    </abgeleiteteWörter>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen>
    <K>jm. Unterricht geben</K>
    <K>jm. Unterricht erteilen</K>
    <K>Unterricht nehmen</K>
    <K>Unterricht erhalten</K>
    <K>den Unterricht besuchen</K>
    <K>am Unterricht teilnehmen</K>
    <K>dem Unterricht fernbleiben</K>
    <K>den Unterricht schwänzen</K>
    <K>der Unterricht fällt aus</K>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>课，课程</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>jm. Unterricht in Englisch geben</Satz>
          <Übersetzung>用英语给人上课</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/98.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Firma</Stichwort>
  <Einheit>6</Einheit>
  <Anteil>Text</Anteil>
  <Genus>die</Genus>
  <Pluralform>Firmen</Pluralform>
  <GenitivSingular>Firma</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <_K>Baufirma</_K>
      <K_>Firmenchef</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>公司</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Ich arbeite bei Firma Borsch.</Satz>
          <Übersetzung>我在公司工作。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/39.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Bier</Stichwort>
  <Einheit>5</Einheit>
  <Anteil>Einführung</Anteil>
  <Genus>das</Genus>
  <Pluralform>Biere</Pluralform>
  <GenitivSingular/>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Bierflasche</K_>
      <K_>Bierglas</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen>
    <K>ein Glas Bier</K>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>啤酒</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Trinken Sie Bier?</Satz>
          <Übersetzung>喝啤酒吗？</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Wollen wir nicht etwas Bier?</Satz>
          <Übersetzung>我们不买点啤酒吗？</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/468.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv"><Stichwort>Tugend</Stichwort><Einheit>3</Einheit><Anteil>2</Anteil><Genus>die</Genus><Pluralform>Tugenden</Pluralform><GenitivSingular>Tugend</GenitivSingular><zusammengesetzteWörter><KompositaCollection></KompositaCollection><abgeleiteteWörter></abgeleiteteWörter></zusammengesetzteWörter><Synonymegruppe></Synonymegruppe><Antonymegruppe></Antonymegruppe><Kollokationen><K>Tugenden bündeln</K></Kollokationen><AllgemeineErläuterungen><Eintrag><Chinesisch>道德</Chinesisch><BeispielSammlung></BeispielSammlung></Eintrag></AllgemeineErläuterungen></Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/99.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true" Bild="99.jpg">Flasche</Stichwort>
  <Einheit>5</Einheit>
  <Anteil>Übungen</Anteil>
  <Genus>die</Genus>
  <Pluralform>Flaschen</Pluralform>
  <GenitivSingular>Flasche</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <_K>Bierflasche</_K>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen>
    <K>eine Flasche Bier</K>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>瓶</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Möchten Sie eine oder zwei Flaschen Wein?</Satz>
          <Übersetzung>您要一瓶酒还是两瓶？</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/298.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
<Stichwort Audio="true">Magen</Stichwort>
<Einheit>9</Einheit>
<Anteil>Einführung</Anteil>
<Genus>der</Genus>
<Pluralform>Mägen</Pluralform>
<GenitivSingular/>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K>Hühnermagen</_K>
		<K_>Magenbeschwerden</K_>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>胃</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Mein Magen tut mir weh.</Satz>
				<Übersetzung>我的胃疼。</Übersetzung>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/226.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
<Stichwort>Kellner</Stichwort>
<Einheit>5</Einheit>
<Anteil>Text</Anteil>
<Genus>der</Genus>
<Pluralform>Kellner</Pluralform>
<GenitivSingular/>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter><hierzu category="Substantiv">Kellnerin</hierzu>
	<hierzu category="Verben">kellnern</hierzu>
	</abgeleiteteWörter></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K>nach dem Kellner rufen</K>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>服务员</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Der Kellner ist sehr nett.</Satz>
				<Übersetzung>这位服务员非常友好。</Übersetzung>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/268.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
<Stichwort>Klößchen</Stichwort>
<Einheit>5</Einheit>
<Anteil>Text</Anteil>
<Genus>das</Genus>
<Pluralform>Klößchen</Pluralform>
<GenitivSingular/>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		
	</KompositaCollection>
	<abgeleiteteWörter/>
</zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>

</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>小丸子</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Es gibt zu Mittag Klößchen.</Satz>
				<Übersetzung>中午有小丸子吃。</Übersetzung>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>
