=== Leidenschaft/Deutsch-Lernen/Wort/example/NounModel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Entry (Stichwort, Aussprache*, Einheit*, Anteil*,
Genus*, Pluralform*, GenitivSingular*, zusammengesetzteWörter,
Synonymegruppe,
Antonymegruppe,Kollokationen,AllgemeineErläuterungen,Comment?)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Aussprache (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT Genus (#PCDATA)>
<!ELEMENT Pluralform (#PCDATA)>
<!ELEMENT GenitivSingular (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_)*>
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ELEMENT Comment (#PCDATA)>
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>    
  <!ATTLIST K link CDATA #IMPLIED>    
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>
<!ATTLIST Stichwort link CDATA #IMPLIED>
<!ATTLIST Stichwort Band CDATA #IMPLIED>
<!ATTLIST Stichwort Bild CDATA #IMPLIED>
<!ATTLIST Stichwort Audio CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/Wort/63.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Dienstag</Stichwort>
  <Einheit>3</Einheit>
  <Anteil>Hörverstehen</Anteil>
  <Genus>der</Genus>
  <Pluralform>Dienstage</Pluralform>
  <GenitivSingular/>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Dienstagabend</K_>
      <K_>Dienstagmittag</K_>
      <K_>Dienstagmorgen</K_>
      <K_>Dienstagnachmittag</K_>
      <K_>Dienstagnacht</K_>
      <K_>Dienstagvormittag</K_>
    </KompositaCollection>
    <abgeleiteteWörter>
      <hierzu category="Adjektiv">dienstags</hierzu>
    </abgeleiteteWörter>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>星期二</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Morgen ist Dienstag.</Satz>
          <Übersetzung>明天是周二。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/256.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Ingenieur</Stichwort>
  <Einheit>4</Einheit>
  <Anteil>Text</Anteil>
  <Genus>der</Genus>
  <Pluralform>Ingenieure</Pluralform>
  <GenitivSingular>Ingenieurs</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Bauingenieur (建筑工程师)</K_>
      <K_>Elektroingenieur</K_>
      <K_>Maschinenbauingenieur (机械制造工程师)</K_>
    </KompositaCollection>
    <abgeleiteteWörter>
      <hierzu category="Substantiv">Ingenieurin</hierzu>
    </abgeleiteteWörter>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>工程师</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Mein Vater ist Ingenieur.</Satz>
          <Übersetzung>我爸是工程师。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/300.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
<Stichwort Audio="true">Management</Stichwort>
<Einheit>8</Einheit>
<Anteil>Text</Anteil>
<Genus>das</Genus>
<Pluralform>o.Pl.</Pluralform>
<GenitivSingular/>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>管理</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Wer studiert Management?</Satz>
				<Übersetzung>谁在学管理学？</Übersetzung>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/69.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Ei</Stichwort>
  <Einheit>5</Einheit>
  <Anteil>Einführung</Anteil>
  <Genus>das</Genus>
  <Pluralform>Eier</Pluralform>
  <GenitivSingular/>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Eizelle (卵细胞)</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>鸡蛋</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Woher kommt das Ei?</Satz>
          <Übersetzung>这个鸡蛋哪来的?</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/297.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
<Stichwort>Mädchen</Stichwort>
<Einheit>7</Einheit>
<Anteil>Text</Anteil>
<Genus>das</Genus>
<Pluralform>Mädchen</Pluralform>
<GenitivSingular/>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K>Schulmädchen</_K>
		<K_>Mädchenschule</K_>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>姑娘</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Frau Mayer hat zwei Kinder,ein Mädchen und einen Jungen.</Satz>
				<Übersetzung>玛雅女士有两个孩子，一个女孩一个男孩。</Übersetzung>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/466.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv"><Stichwort>Mahnung</Stichwort><Einheit>3</Einheit><Anteil>1</Anteil><Genus>die</Genus><Pluralform>Mahnungen</Pluralform><GenitivSingular>Mahnung</GenitivSingular><zusammengesetzteWörter><KompositaCollection></KompositaCollection><abgeleiteteWörter></abgeleiteteWörter></zusammengesetzteWörter><Synonymegruppe></Synonymegruppe><Antonymegruppe></Antonymegruppe><Kollokationen></Kollokationen><AllgemeineErläuterungen><Eintrag><Chinesisch>提醒</Chinesisch><BeispielSammlung><Beispiel><Satz>Mahnung an Kaiser</Satz><Übersetzung>提醒皇上</Übersetzung></Beispiel></BeispielSammlung></Eintrag></AllgemeineErläuterungen></Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/160.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true" Bild="160.jpg">Uhr</Stichwort>
  <Einheit>3</Einheit>
  <Anteil>Text</Anteil>
  <Genus>die</Genus>
  <Pluralform>Uhren</Pluralform>
  <GenitivSingular>Uhr</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <_K>Uhrband</_K>
      <_K>Uhrzeiger</_K>
      <_K>Uhrmacher</_K>
      <_K>Uhrwerk</_K>
      <_K>Uhrzeigersinn</_K>
      <_K>Uhrzeit</_K>
      <K_>Armbanduhr</K_>
      <K_>Standuhr</K_>
      <K_>Taschenuhr</K_>
      <K_>Bahnhofsuhr</K_>
      <K_>Kirchenuhr</K_>
      <K_>Turmuhr</K_>
      <K_>Digitaluhr</K_>
      <K_>Eieruhr</K_>
      <K_>Sonnenuhr</K_>
      <K_>Stoppuhr</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen>
    <K>eine wasserdichte Uhr</K>
    <K>das Zifferblatt einer Uhr</K>
    <K>die Zieger einer Uhr</K>
    <K>die Uhr tickt</K>
    <K>die Uhr geht vor</K>
    <K>die Uhr geht nach</K>
    <K>die Uhr geht richtig</K>
    <K>die Uhr bleibt stehen</K>
    <K>eine Uhr aufziehen</K>
    <K>eine Uhr zurückstellen</K>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>表，钟</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Meine Uhr geht jeden Tag zehn Minuten vor.</Satz>
          <Übersetzung>我的表每天走快十分钟。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
    <Eintrag>
      <Chinesisch>小时</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Wir treffen uns gegen elf Uhr.</Satz>
          <Übersetzung>我们十一点左右碰面。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/100.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Fleisch</Stichwort>
  <Einheit>5</Einheit>
  <Anteil>Einführung</Anteil>
  <Genus>das</Genus>
  <Pluralform>o.Pl.</Pluralform>
  <GenitivSingular>Fleischs</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Fleischgericht (荤菜)</K_>
      <_K>Hühnerfleich (鸡肉)</_K>
      <_K>Rindfleich (牛肉)</_K>
      <_K>Schweinefleich (猪肉)</_K>
      <_K>Fruchtfleich (果肉)</_K>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>肉</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Essen Sie bitte nicht zu viel Fleisch.</Satz>
          <Übersetzung>请您不要吃太多的肉。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>
