=== Leidenschaft/Deutsch-Lernen/Wort/example/NounModel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Entry (Stichwort, Aussprache*, Einheit*, Anteil*,
Genus*, Pluralform*, GenitivSingular*, zusammengesetzteWörter,
Synonymegruppe,
Antonymegruppe,Kollokationen,AllgemeineErläuterungen,Comment?)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Aussprache (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT Genus (#PCDATA)>
<!ELEMENT Pluralform (#PCDATA)>
<!ELEMENT GenitivSingular (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_)*>
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ELEMENT Comment (#PCDATA)>
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>    
  <!ATTLIST K link CDATA #IMPLIED>    
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>
<!ATTLIST Stichwort link CDATA #IMPLIED>
<!ATTLIST Stichwort Band CDATA #IMPLIED>
<!ATTLIST Stichwort Bild CDATA #IMPLIED>
<!ATTLIST Stichwort Audio CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/194.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Wohngemeinschaft</Stichwort>
  <Einheit>6</Einheit>
  <Anteil>Einfürung</Anteil>
  <Genus>die</Genus>
  <Pluralform>Wohngemeinschaft</Pluralform>
  <GenitivSingular>Wohngemeinschafts</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection/>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe>
    <Sym>WG</Sym>
  </Synonymegruppe>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>集体宿舍</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Ich zog gestern in die Wohngemeinschaft ein.</Satz>
          <Übersetzung>昨天我搬进了集体宿舍。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/53.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Cappuccino</Stichwort>
  <Einheit>5</Einheit>
  <Anteil>Hörverstehen</Anteil>
  <Genus>der</Genus>
  <Pluralform>Cappuccinos</Pluralform>
  <GenitivSingular/>
  <zusammengesetzteWörter>
    <KompositaCollection/>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>卡布奇诺咖啡</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Ich hätte gern einen Cappuccino.</Satz>
          <Übersetzung>我想要一杯咖啡。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/361.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
<Stichwort Audio="true">Polizei</Stichwort>
<Einheit>4</Einheit>
<Anteil>Übungen</Anteil>
<Genus>die</Genus>
<Pluralform>Polizeien</Pluralform>
<GenitivSingular/>

<zusammengesetzteWörter>
	<KompositaCollection>
    <K_>Polizeibeamte</K_>
    <K_>Verkehrspolizei</K_>
  </KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
  <K>Polizei rufen</K>
</Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
    <Chinesisch> 警察,警察局</Chinesisch>
  <BeispielSammlung>
    <Beispiel>
      <Satz>Die Polizei ist dort.</Satz>
      <Übersetzung>警察在那里。</Übersetzung>
    </Beispiel>
    <Beispiel>
      <Satz>Ich muss morgen zu Polizei.</Satz>
      <Übersetzung>我必须明天去警察局。</Übersetzung>
    </Beispiel>
  </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/6.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort>Alkohol</Stichwort>
  <Einheit>4</Einheit>
  <Anteil>Text</Anteil>
  <Genus>der</Genus>
  <Pluralform>Alkohole</Pluralform>
  <GenitivSingular>Alkohols</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Alkoholtest</K_>
    </KompositaCollection>
    <abgeleiteteWörter>
      <hierzu category="Adjektiv">alkoholisch</hierzu>
      <hierzu category="Adjektiv">alkoholfrei</hierzu>
      <hierzu category="Substantiv">Alkoholiker</hierzu>
    </abgeleiteteWörter>
  </zusammengesetzteWörter>
  <Synonymegruppe>
    <Sym>alkoholische Getränke</Sym>
  </Synonymegruppe>
  <Antonymegruppe>
    <Anm>alkoholfreie Getränke</Anm>
  </Antonymegruppe>
  <Kollokationen>
    <K>Alkohol trinken</K>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>酒精饮料</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Sie trinkt auch keinen Alkohol.</Satz>
          <Übersetzung>她也不喝酒。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
    <Eintrag>
      <Chinesisch>酒精</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Das Beer hat 5% Alkohol.</Satz>
          <Übersetzung>这种啤酒含5%的酒精。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Er leidet under den Folgen des Alkohols.</Satz>
          <Übersetzung>他受着酒精的折磨。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/29.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Bein</Stichwort>
  <Einheit>9</Einheit>
  <Anteil>Einführung</Anteil>
  <Genus>das</Genus>
  <Pluralform>Beine</Pluralform>
  <GenitivSingular>Beines</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection/>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen>
    <K>etwas hat Beine bekommen</K>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>腿</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Mein Schlüssel bekommt Beine.</Satz>
          <Übersetzung>我的钥匙丢了。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Es gibt Stuhn mit drei Beinen.</Satz>
          <Übersetzung>有的椅子只有三条腿。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Der Kranke steht gerade mit einem Bein im Grabe.</Satz>
          <Übersetzung>这位病人已经病入膏肓了。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Der Kranke war wieder auf den Beinen.</Satz>
          <Übersetzung>病人已经康复了。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Er ist ein Mann mit beiden Beinen fest im Leben.</Satz>
          <Übersetzung>他是一个脚踏实地的人。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Viele Japanische Studenten stehen auf eigenen Beinen.</Satz>
          <Übersetzung>许多日本的大学生自食其力。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/30.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort>Benzin</Stichwort>
  <Einheit>8</Einheit>
  <Anteil>Leseverstehen</Anteil>
  <Genus>das</Genus>
  <Pluralform>Benzine</Pluralform>
  <GenitivSingular>Benzins</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Benzinmotor</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>汽油</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Er hat ein paar Euro für Benzin bezahlt.</Satz>
          <Übersetzung>他买汽油付了些钱。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/68.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true">Ecke</Stichwort>
  <Einheit>6</Einheit>
  <Anteil>Text</Anteil>
  <Genus>die</Genus>
  <Pluralform>Ecken</Pluralform>
  <GenitivSingular/>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <K_>Eckschrank(角橱)</K_>
      <K_>Eckball([足球])</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>角落</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Die katze läuft in die Ecke.</Satz>
          <Übersetzung>猫跑到角落了。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Ich suche meine Tasche an allen Ecken und Enden. Leider finde ich ihr nicht.</Satz>
          <Übersetzung>我到处都找遍了手提包可是还没找到。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/91.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE Entry SYSTEM "NounModel.dtd"><?xml-stylesheet type="text/xsl" href="NounRenderTemplate2.xslt"?><Entry category="Substantiv">
  <Stichwort Audio="true" Bild="91.jpg">Farbe</Stichwort>
  <Einheit>7</Einheit>
  <Anteil>Text</Anteil>
  <Genus>die</Genus>
  <Pluralform>Farben</Pluralform>
  <GenitivSingular>Farbe</GenitivSingular>
  <zusammengesetzteWörter>
    <KompositaCollection>
      <_K>Augenfarbe</_K>
      <K_>Farbefernsehen</K_>
      <_K>Gesichtsfarbe</_K>
      <_K>Haarfarbe</_K>
      <K_>Farbofoto</K_>
    </KompositaCollection>
    <abgeleiteteWörter/>
  </zusammengesetzteWörter>
  <Synonymegruppe/>
  <Antonymegruppe/>
  <Kollokationen/>
  <AllgemeineErläuterungen>
    <Eintrag>
      <Chinesisch>颜色</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Die Farbe steht mir nicht besonders.</Satz>
          <Übersetzung>这种颜色不太适合我。</Übersetzung>
        </Beispiel>
        <Beispiel>
          <Satz>Die Farbe der Ampel sind rot, gelb und grün.</Satz>
          <Übersetzung>交通灯的颜色是红黄绿。</Übersetzung>
        </Beispiel>
      </BeispielSammlung>
    </Eintrag>
  </AllgemeineErläuterungen>
</Entry>
