=== Leidenschaft/Deutsch-Lernen/Wort/AdjModel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Entry (Stichwort,Einheit,Anteil*,zusammengesetzteWörter,Synonymegruppe,Antonymegruppe,Kollokationen,AllgemeineErläuterungen)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_)*>
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben | Adverb | Konnektor | Partikel | Interjektion | Pronomen | Artikel) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>
  <!ATTLIST K link CDATA #IMPLIED>   
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/Wort/A93.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>ziemlich</Stichwort>
<Einheit>6</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>相当(改)</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Er trinkt ziemlich viel.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A77.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>unterschiedlich</Stichwort>
<Einheit>5</Einheit>
<Anteil>Leseverstehen</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>有区别的，不同的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Die Spezialitäten sind unterschiedlich.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A49.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>richtig</Stichwort>
<Einheit>4</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>正确的，正式的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Das ist richtig.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A53.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>doch</Stichwort>
<Einheit>4</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>却，仍然</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Lerst du nicht Deutsch?-Doch.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A25.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>halb</Stichwort>
<Einheit>3</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>一半</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Ich frühstücke um halb acht.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A39.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>jetzt</Stichwort>
<Einheit>2</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>现在，如今</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Jetzt öffnen Sie bitte die Bücher,Seite vier.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A8.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>gern</Stichwort>
<Einheit>2</Einheit>
<Anteil>Übungen</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>乐意，喜欢</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Ich höre gern Musik und chatte auch gern.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>
