=== Leidenschaft/Deutsch-Lernen/Wort/AdjModel.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Entry (Stichwort,Einheit,Anteil*,zusammengesetzteWörter,Synonymegruppe,Antonymegruppe,Kollokationen,AllgemeineErläuterungen)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_)*>
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben | Adverb | Konnektor | Partikel | Interjektion | Pronomen | Artikel) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>
  <!ATTLIST K link CDATA #IMPLIED>   
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/Wort/A16.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>alt</Stichwort>
<Einheit>3</Einheit>
<Anteil>Hörverstehen</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>年老的，旧的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Ich bin 20 Jahre alt. Die Zeitung ist alt.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A86.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>griechisch</Stichwort>
<Einheit>5</Einheit>
<Anteil>Leseverstehen</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>希腊的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Wie klingt die griechische Sprache?</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A19.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>bald</Stichwort>
<Einheit>4</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>不久，很快</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Er kommt bald.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A26.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>meistens</Stichwort>
<Einheit>3</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>通常</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Ich früstücke meistens sehr gut.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A12.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>aktiv</Stichwort>
<Einheit>3</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>积极的，活跃的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Die Studenten sind im Unterricht aktiv.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A31.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>nie</Stichwort>
<Einheit>3</Einheit>
<Anteil>Text</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>从没有，绝不</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Du hast nie Zeit für deine Freunde.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A36.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>gerade</Stichwort>
<Einheit>2</Einheit>
<Anteil>Leseverstehen</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>直的，水平的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Ich lerne gerade Deutsch.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/A13.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>    <!DOCTYPE Entry SYSTEM "AdjModel.dtd">    <?xml-stylesheet type="text/xsl" href="AdjRenderTemplate.xslt"?><Entry category="Adjektiv">
<Stichwort>interessant</Stichwort>
<Einheit>3</Einheit>
<Anteil>Übungen</Anteil>

<zusammengesetzteWörter>
	<KompositaCollection>
		<_K/>
		<K_/>
	</KompositaCollection>
	<abgeleiteteWörter/></zusammengesetzteWörter>

<Synonymegruppe>
	<Sym/>
</Synonymegruppe>
<Antonymegruppe>
	<Anm/>
</Antonymegruppe>

<Kollokationen>
<K/>
</Kollokationen>

<AllgemeineErläuterungen>
	<Eintrag>
		<Chinesisch>有趣的，有吸引力的</Chinesisch>
		<BeispielSammlung>
			<Beispiel>
				<Satz>Das ist aber interessant.</Satz>
				<Übersetzung/>
			</Beispiel>
		</BeispielSammlung>
	</Eintrag>
</AllgemeineErläuterungen>

</Entry>
