=== Leidenschaft/Deutsch-Lernen/Wort/VerbenModel.dtd
<!ELEMENT Entry (Stichwort,Einheit,Anteil,Konjugation,zusammengesetzteWörter,Synonymegruppe,Antonymegruppe,
Kollokationen,AllgemeineErläuterungen)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_|_K_)*>
  <!ELEMENT Konjugation (Präsen,Präteritum,Perfekt)>
  <!ELEMENT Präsen (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT Präteritum (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT Perfekt (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT ich (#PCDATA)>
  <!ELEMENT du (#PCDATA)>
  <!ELEMENT er_sie_es (#PCDATA)>
  <!ELEMENT wir (#PCDATA)>
  <!ELEMENT ihr (#PCDATA)>
  <!ELEMENT sie_Sie (#PCDATA)>
  
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT _K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>    
  <!ATTLIST K link CDATA #IMPLIED>    
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>
<!ATTLIST hierzu chinesisch CDATA #IMPLIED>  
<!ATTLIST hierzu trennbar CDATA #IMPLIED>  
<!ATTLIST K_ chinesisch CDATA #IMPLIED>  
<!ATTLIST _K chinesisch CDATA #IMPLIED>  
<!ATTLIST _K_ chinesisch CDATA #IMPLIED>  
<!ATTLIST K_ category CDATA #IMPLIED>  
<!ATTLIST _K category CDATA #IMPLIED>  
<!ATTLIST _K_ category CDATA #IMPLIED>  
<!ATTLIST Perfekt hilfsverb CDATA #REQUIRED>
<!ATTLIST Eintrag transitiv CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V89.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>surfen</Stichwort>
	<Einheit>6</Einheit>
	<Anteil>Übungen</Anteil>
	<Konjugation>
				<Präsen>
					<ich>surfe</ich>
					<du>surfst</du>
					<er_sie_es>surft</er_sie_es>
					<wir>surfen</wir>
					<ihr>surft</ihr>
					<sie_Sie>surfen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>surfte</ich>
					<du>surftest</du>
					<er_sie_es>surfte</er_sie_es>
					<wir>surften</wir>
					<ihr>surftet</ihr>
					<sie_Sie>surften</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gesurft</ich>
					<du>hast gesurft</du>
					<er_sie_es>hat gesurft</er_sie_es>
					<wir>haben gesurft</wir>
					<ihr>habt gesurft</ihr>
					<sie_Sie>haben gesurft</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>冲浪运动，网络漫游</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Er surft gern im Internet.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/example/V1.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort Bild="V1.jpg">kommen</Stichwort>
	<Einheit>1</Einheit>
	<Anteil>2</Anteil>
	<Konjugation>
				<Präsen>
					<ich>komme</ich>
					<du>kommst</du>
					<er_sie_es>kommt</er_sie_es>
					<wir>kommen</wir>
					<ihr>kommt</ihr>
					<sie_Sie>kommen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>kam</ich>
					<du>kamst</du>
					<er_sie_es>kam</er_sie_es>
					<wir>kamen</wir>
					<ihr>kamt</ihr>
					<sie_Sie>kamen</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="sein">	
					<ich>bin gekommen</ich>
					<du>bist gekommen</du>
					<er_sie_es>ist gekommen</er_sie_es>
					<wir>sind gekommen</wir>
					<ihr>seid gekommen</ihr>
					<sie_Sie>sind gekommen</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
      <K>nach Hause kommen</K>
      <K>zu Erfolg kommen</K>
      <K>jemandem zu Hilfe kommen</K>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="FALSE">
					
					<Chinesisch>来</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Woher kommen Sie?</Satz>
          <Übersetzung>你来自哪？</Übersetzung>
					</Beispiel>
          <Beispiel>
              <Satz>Der kalte Wind kommt von Norden.</Satz>
              <Übersetzung>寒风自北方来。</Übersetzung>
          </Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
      </AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V107.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>auspacken</Stichwort>
	<Einheit>7</Einheit>
	<Anteil>Leseverstehen</Anteil>
	<Konjugation>
				<Präsen>
					<ich>packe aus</ich>
					<du>packst aus</du>
					<er_sie_es>packt aus</er_sie_es>
					<wir>packen aus</wir>
					<ihr>packt aus</ihr>
					<sie_Sie>packen aus</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>packte aus</ich>
					<du>packtest aus</du>
					<er_sie_es>packte aus</er_sie_es>
					<wir>packten aus</wir>
					<ihr>packtet aus</ihr>
					<sie_Sie>packten aus</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe ausgepackt</ich>
					<du>hast ausgepackt</du>
					<er_sie_es>hat ausgepackt</er_sie_es>
					<wir>haben ausgepackt</wir>
					<ihr>habt ausgepackt</ihr>
					<sie_Sie>haben ausgepackt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>打开（包装），取出</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Er packt das Geschenk sofort aus.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V88.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>legen</Stichwort>
	<Einheit>6</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>lege</ich>
					<du>legst</du>
					<er_sie_es>legt</er_sie_es>
					<wir>legen</wir>
					<ihr>legt</ihr>
					<sie_Sie>legen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>legte</ich>
					<du>legtest</du>
					<er_sie_es>legte</er_sie_es>
					<wir>legten</wir>
					<ihr>legtet</ihr>
					<sie_Sie>legten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gelegt</ich>
					<du>hast gelegt</du>
					<er_sie_es>hat gelegt</er_sie_es>
					<wir>haben gelegt</wir>
					<ihr>habt gelegt</ihr>
					<sie_Sie>haben gelegt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>平放，摆；躺，卧</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Er legt die Zeitung auf den Tisch.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V66.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>danken</Stichwort>
	<Einheit>5</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>danke</ich>
					<du>dankst</du>
					<er_sie_es>dankt</er_sie_es>
					<wir>danken</wir>
					<ihr>dankt</ihr>
					<sie_Sie>danken</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>dankte</ich>
					<du>danktest</du>
					<er_sie_es>dankte</er_sie_es>
					<wir>dankten</wir>
					<ihr>danktet</ihr>
					<sie_Sie>dankten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gedankt</ich>
					<du>hast gedankt</du>
					<er_sie_es>hat gedankt</er_sie_es>
					<wir>haben gedankt</wir>
					<ihr>habt gedankt</ihr>
					<sie_Sie>haben gedankt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>感谢</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Ich danke dir für das Essen.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V47.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
  <Stichwort>kochen</Stichwort>
  <Einheit>4</Einheit>
  <Anteil>Text</Anteil>
  <Konjugation>
    <Präsen>
      <ich>koche</ich>
      <du>kochst</du>
      <er_sie_es>kocht</er_sie_es>
      <wir>kochen</wir>
      <ihr>kocht</ihr>
      <sie_Sie>kochen</sie_Sie>
    </Präsen>
    <Präteritum>
      <ich>kochte</ich>
      <du>kochtest</du>
      <er_sie_es>kochte</er_sie_es>
      <wir>kochten</wir>
      <ihr>kochtet</ihr>
      <sie_Sie>kochten</sie_Sie>
    </Präteritum>
    <Perfekt hilfsverb="haben">
      <ich>habe gekocht</ich>
      <du>hast gekocht</du>
      <er_sie_es>hat gekocht</er_sie_es>
      <wir>haben gekocht</wir>
      <ihr>habt gekocht</ihr>
      <sie_Sie>haben gekocht</sie_Sie>
    </Perfekt>
  </Konjugation>


  <zusammengesetzteWörter>
    <KompositaCollection>
    </KompositaCollection>
    <abgeleiteteWörter>
    </abgeleiteteWörter>
  </zusammengesetzteWörter>
  <Synonymegruppe>
    <Sym/>
  </Synonymegruppe>
  <Antonymegruppe>
    <Anm/>
  </Antonymegruppe>

  <Kollokationen>
    <K/>
  </Kollokationen>
  <AllgemeineErläuterungen>
    <Eintrag transitiv="">

      <Chinesisch>做菜饭；煮，烧，烹调</Chinesisch>
      <BeispielSammlung>
        <Beispiel>
          <Satz>Was kochst du da?</Satz>
          <Übersetzung/>
        </Beispiel>
      </BeispielSammlung>

    </Eintrag>
  </AllgemeineErläuterungen>


</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V120.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>bleiben</Stichwort>
	<Einheit>8</Einheit>
	<Anteil>Übungen</Anteil>
	<Konjugation>
				<Präsen>
					<ich>bleibe</ich>
					<du>bleibst</du>
					<er_sie_es>bleibt</er_sie_es>
					<wir>bleiben</wir>
					<ihr>bleibt</ihr>
					<sie_Sie>bleiben</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>blieb</ich>
					<du>bliebst</du>
					<er_sie_es>blieb</er_sie_es>
					<wir>blieben</wir>
					<ihr>bliebt</ihr>
					<sie_Sie>blieben</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="sein">	
					<ich>bin geblieben</ich>
					<du>bist geblieben</du>
					<er_sie_es>ist geblieben</er_sie_es>
					<wir>sind geblieben</wir>
					<ihr>seid geblieben</ihr>
					<sie_Sie>sind geblieben</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>待，停留</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Ich bin zu Hause geblieben.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V152.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>tun</Stichwort>
	<Einheit>9</Einheit>
	<Anteil>Leseverstehen</Anteil>
	<Konjugation>
				<Präsen>
					<ich>tue</ich>
					<du>tust</du>
					<er_sie_es>tut</er_sie_es>
					<wir>tun</wir>
					<ihr>tut</ihr>
					<sie_Sie>tun</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>tat</ich>
					<du>tatest</du>
					<er_sie_es>tat</er_sie_es>
					<wir>taten</wir>
					<ihr>tatet</ihr>
					<sie_Sie>taten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe getan</ich>
					<du>hast getan</du>
					<er_sie_es>hat getan</er_sie_es>
					<wir>haben getan</wir>
					<ihr>habt getan</ihr>
					<sie_Sie>haben getan</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>做，干</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Was soll ich tun?</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>
