=== Leidenschaft/Deutsch-Lernen/Wort/VerbenModel.dtd
<!ELEMENT Entry (Stichwort,Einheit,Anteil,Konjugation,zusammengesetzteWörter,Synonymegruppe,Antonymegruppe,
Kollokationen,AllgemeineErläuterungen)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_|_K_)*>
  <!ELEMENT Konjugation (Präsen,Präteritum,Perfekt)>
  <!ELEMENT Präsen (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT Präteritum (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT Perfekt (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT ich (#PCDATA)>
  <!ELEMENT du (#PCDATA)>
  <!ELEMENT er_sie_es (#PCDATA)>
  <!ELEMENT wir (#PCDATA)>
  <!ELEMENT ihr (#PCDATA)>
  <!ELEMENT sie_Sie (#PCDATA)>
  
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT _K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>    
  <!ATTLIST K link CDATA #IMPLIED>    
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>
<!ATTLIST hierzu chinesisch CDATA #IMPLIED>  
<!ATTLIST hierzu trennbar CDATA #IMPLIED>  
<!ATTLIST K_ chinesisch CDATA #IMPLIED>  
<!ATTLIST _K chinesisch CDATA #IMPLIED>  
<!ATTLIST _K_ chinesisch CDATA #IMPLIED>  
<!ATTLIST K_ category CDATA #IMPLIED>  
<!ATTLIST _K category CDATA #IMPLIED>  
<!ATTLIST _K_ category CDATA #IMPLIED>  
<!ATTLIST Perfekt hilfsverb CDATA #REQUIRED>
<!ATTLIST Eintrag transitiv CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V51.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>anrufen</Stichwort>
	<Einheit>4</Einheit>
	<Anteil>Übungen</Anteil>
	<Konjugation>
				<Präsen>
					<ich>rufe an</ich>
					<du>rufst an</du>
					<er_sie_es>ruft an</er_sie_es>
					<wir>rufen an</wir>
					<ihr>ruft an</ihr>
					<sie_Sie>rufen an</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>rief an</ich>
					<du>riefst an</du>
					<er_sie_es>rief an</er_sie_es>
					<wir>riefen an</wir>
					<ihr>rieft an</ihr>
					<sie_Sie>riefen an</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe angerufen</ich>
					<du>hast angerufen</du>
					<er_sie_es>hat angerufen</er_sie_es>
					<wir>haben angerufen</wir>
					<ihr>habt angerufen</ihr>
					<sie_Sie>haben angerufen</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>打电话</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Rufen Sie mich bitte an!</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V55.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>leidtun</Stichwort>
	<Einheit>4</Einheit>
	<Anteil>Intentionen</Anteil>
	<Konjugation>
				<Präsen>
          <ich>tu leid</ich>
					<du>tust leid</du>
          <er_sie_es>tut leid</er_sie_es>
          <wir>tun leid</wir>
          <ihr>tut leid</ihr>
          <sie_Sie>tun leid</sie_Sie>
				</Präsen>
				<Präteritum>
          <ich>tat leid</ich>
          <du>tatest leid</du>
					<er_sie_es>tat leid</er_sie_es>
          <wir>taten leid</wir>
          <ihr>tatet leid</ihr>
          <sie_Sie>taten leid</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">
          <ich>habe leidgetan</ich>
          <du>hast leidgetan</du>
          <er_sie_es>hat leidgetan</er_sie_es>
          <wir>haben leidgetan</wir>
          <ihr>habt leidgetan</ihr>
          <sie_Sie>haben leidgetan</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>遗憾，抱歉</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Es tut mir leid.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V17.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>wohnen</Stichwort>
	<Einheit>2</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>wohne</ich>
					<du>wohnst</du>
					<er_sie_es>wohnt</er_sie_es>
					<wir>wohnen</wir>
					<ihr>wohnt</ihr>
					<sie_Sie>wohnen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>wohnte</ich>
					<du>wohntest</du>
					<er_sie_es>wohnte</er_sie_es>
					<wir>wohnten</wir>
					<ihr>wohntet</ihr>
					<sie_Sie>wohnten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gewohnt</ich>
					<du>hast gewohnt</du>
					<er_sie_es>hat gewohnt</er_sie_es>
					<wir>haben gewohnt</wir>
					<ihr>habt gewohnt</ihr>
					<sie_Sie>haben gewohnt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>居住</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Wir wohnen im Studentenwohnheim.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V31.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>laufen</Stichwort>
	<Einheit>3</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>laufe</ich>
					<du>läufst</du>
					<er_sie_es>läuft</er_sie_es>
					<wir>laufen</wir>
					<ihr>lauft</ihr>
					<sie_Sie>laufen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>lief</ich>
					<du>liefst</du>
					<er_sie_es>lief</er_sie_es>
					<wir>liefen</wir>
					<ihr>lieft</ihr>
					<sie_Sie>liefen</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="sein">	
					<ich>bin gelaufen</ich>
					<du>bist gelaufen</du>
					<er_sie_es>ist gelaufen</er_sie_es>
					<wir>sind gelaufen</wir>
					<ihr>seid gelaufen</ihr>
					<sie_Sie>sind gelaufen</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>跑，跑步</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Ich laufe schnell.</Satz>
            <Übersetzung>我跑得很快。</Übersetzung>
					</Beispiel>
            <Beispiel>
              <Satz>Der Hund läuft hinter das Auto.</Satz>
              <Übersetzung>这只狗跑到车后面去了。</Übersetzung>
            </Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
  <Comment>hinter ___ Auto https://de.wiktionary.org/wiki/laufen Der Hund läuft hinter dem Auto her</Comment>
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V112.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>dauern</Stichwort>
	<Einheit>8</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>dauere</ich>
					<du>daure</du>
					<er_sie_es>dauerst</er_sie_es>
					<wir>dauert</wir>
					<ihr>dauern</ihr>
					<sie_Sie>dauert</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>Sie</ich>
					<du>dauerte</du>
					<er_sie_es>dauertest</er_sie_es>
					<wir>dauerte</wir>
					<ihr>dauerten</ihr>
					<sie_Sie>dauertet</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gedauert</ich>
					<du>hast gedauert</du>
					<er_sie_es>hat gedauert</er_sie_es>
					<wir>haben gedauert</wir>
					<ihr>habt gedauert</ihr>
					<sie_Sie>haben gedauert</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>续，延续</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Die Fahrt dauert drei Stunden.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V142.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>ausruhen</Stichwort>
	<Einheit>9</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>ruhe aus</ich>
					<du>ruhst aus</du>
					<er_sie_es>ruht aus</er_sie_es>
					<wir>ruhen aus</wir>
					<ihr>ruht aus</ihr>
					<sie_Sie>ruhen aus</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>ruhte aus</ich>
					<du>ruhtest aus</du>
					<er_sie_es>ruhte aus</er_sie_es>
					<wir>ruhten aus</wir>
					<ihr>ruhtet aus</ihr>
					<sie_Sie>ruhten aus</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe ausgeruht</ich>
					<du>hast ausgeruht</du>
					<er_sie_es>hat ausgeruht</er_sie_es>
					<wir>haben ausgeruht</wir>
					<ihr>habt ausgeruht</ihr>
					<sie_Sie>haben ausgeruht</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>（劳动后）休息</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Sie haben den ganzen Tag gearbeitet und sollen sich jetzt ausruhen.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V64.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>gefallen</Stichwort>
	<Einheit>5</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>gefalle</ich>
					<du>gefällst</du>
					<er_sie_es>gefällt</er_sie_es>
					<wir>gefallen</wir>
					<ihr>gefallt</ihr>
					<sie_Sie>gefallen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>gefiel</ich>
					<du>gefielst</du>
					<er_sie_es>gefiel</er_sie_es>
					<wir>gefielen</wir>
					<ihr>gefielt</ihr>
					<sie_Sie>gefielen</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="sein">	
					<ich>bin gefallen</ich>
					<du>bist gefallen</du>
					<er_sie_es>ist gefallen</er_sie_es>
					<wir>sind gefallen</wir>
					<ihr>seid gefallen</ihr>
					<sie_Sie>sind gefallen</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>使……喜欢</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Das Restaurant hier gefällt mir sehr.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>
