=== Leidenschaft/Deutsch-Lernen/Wort/VerbenModel.dtd
<!ELEMENT Entry (Stichwort,Einheit,Anteil,Konjugation,zusammengesetzteWörter,Synonymegruppe,Antonymegruppe,
Kollokationen,AllgemeineErläuterungen)>
<!ELEMENT Stichwort (#PCDATA)>
<!ELEMENT Einheit (#PCDATA)>
<!ELEMENT Anteil (#PCDATA)>
<!ELEMENT zusammengesetzteWörter (KompositaCollection,abgeleiteteWörter)>
  <!ELEMENT KompositaCollection (_K|K_|_K_)*>
  <!ELEMENT Konjugation (Präsen,Präteritum,Perfekt)>
  <!ELEMENT Präsen (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT Präteritum (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT Perfekt (ich,du,er_sie_es,wir,ihr,sie_Sie)>
  <!ELEMENT ich (#PCDATA)>
  <!ELEMENT du (#PCDATA)>
  <!ELEMENT er_sie_es (#PCDATA)>
  <!ELEMENT wir (#PCDATA)>
  <!ELEMENT ihr (#PCDATA)>
  <!ELEMENT sie_Sie (#PCDATA)>
  
  <!ELEMENT abgeleiteteWörter (hierzu*)>
  <!ELEMENT _K (#PCDATA)>
  <!ELEMENT K_ (#PCDATA)>
  <!ELEMENT _K_ (#PCDATA)>
  <!ELEMENT hierzu (#PCDATA)>
  <!ELEMENT AllgemeineErläuterungen (Eintrag+)>
  <!ELEMENT Eintrag (Chinesisch,BeispielSammlung)>
  <!ELEMENT Chinesisch (#PCDATA)>
  <!ELEMENT BeispielSammlung (Beispiel*)>
  <!ELEMENT Beispiel (Satz,Übersetzung)>
  <!ELEMENT Satz (#PCDATA)>
  <!ELEMENT Übersetzung (#PCDATA)>  
  <!ELEMENT Synonymegruppe (Sym*)>  
  <!ELEMENT Sym (#PCDATA)>
  <!ELEMENT Antonymegruppe (Anm*)>  
  <!ELEMENT Anm (#PCDATA)>
  <!ELEMENT Kollokationen (K*)>  
  <!ELEMENT K (#PCDATA)>  
  <!ATTLIST hierzu category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST Entry category (Substantiv | Adjektiv | Verben) "Substantiv"> <?Substantiv is the default value?>
  <!ATTLIST _K link CDATA #IMPLIED>    
  <!ATTLIST K link CDATA #IMPLIED>    
  <!ATTLIST K_ link CDATA #IMPLIED>
  <!ATTLIST Sym link CDATA #IMPLIED>  
  <!ATTLIST Anm link CDATA #IMPLIED>  
<!ATTLIST hierzu link CDATA #IMPLIED>
<!ATTLIST hierzu chinesisch CDATA #IMPLIED>  
<!ATTLIST hierzu trennbar CDATA #IMPLIED>  
<!ATTLIST K_ chinesisch CDATA #IMPLIED>  
<!ATTLIST _K chinesisch CDATA #IMPLIED>  
<!ATTLIST _K_ chinesisch CDATA #IMPLIED>  
<!ATTLIST K_ category CDATA #IMPLIED>  
<!ATTLIST _K category CDATA #IMPLIED>  
<!ATTLIST _K_ category CDATA #IMPLIED>  
<!ATTLIST Perfekt hilfsverb CDATA #REQUIRED>
<!ATTLIST Eintrag transitiv CDATA #IMPLIED>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V76.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>zeigen</Stichwort>
	<Einheit>6</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>zeige</ich>
					<du>zeigst</du>
					<er_sie_es>zeigt</er_sie_es>
					<wir>zeigen</wir>
					<ihr>zeigt</ihr>
					<sie_Sie>zeigen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>zeigte</ich>
					<du>zeigtest</du>
					<er_sie_es>zeigte</er_sie_es>
					<wir>zeigten</wir>
					<ihr>zeigtet</ihr>
					<sie_Sie>zeigten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gezeigt</ich>
					<du>hast gezeigt</du>
					<er_sie_es>hat gezeigt</er_sie_es>
					<wir>haben gezeigt</wir>
					<ihr>habt gezeigt</ihr>
					<sie_Sie>haben gezeigt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>给……看</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Sie zeigt ihm die Wohnung.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V63.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>hierherkommen</Stichwort>
	<Einheit>5</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>komme hierher</ich>
					<du>kommst hierher</du>
					<er_sie_es>kommt hierher</er_sie_es>
					<wir>kommen hierher</wir>
					<ihr>kommt hierher</ihr>
					<sie_Sie>kommen hierher</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>kam hierher</ich>
					<du>kamst hierher</du>
					<er_sie_es>kam hierher</er_sie_es>
					<wir>kamen hierher</wir>
					<ihr>kamt hierher</ihr>
					<sie_Sie>kamen hierher</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="sein">	
					<ich>bin hierhergekommen</ich>
					<du>bist hierhergekommen</du>
					<er_sie_es>ist hierhergekommen</er_sie_es>
					<wir>sind hierhergekommen</wir>
					<ihr>seid hierhergekommen</ihr>
					<sie_Sie>sind hierhergekommen</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>到这儿来</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Ich komme oft hierher.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V114.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>verbringen</Stichwort>
	<Einheit>8</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>verbringe</ich>
					<du>verbringst</du>
					<er_sie_es>verbringt</er_sie_es>
					<wir>verbringen</wir>
					<ihr>verbringt</ihr>
					<sie_Sie>verbringen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>verbrachte</ich>
					<du>verbrachtest</du>
					<er_sie_es>verbrachte</er_sie_es>
					<wir>verbrachten</wir>
					<ihr>verbrachtet</ihr>
					<sie_Sie>verbrachten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe verbracht</ich>
					<du>hast verbracht</du>
					<er_sie_es>hat verbracht</er_sie_es>
					<wir>haben verbracht</wir>
					<ihr>habt verbracht</ihr>
					<sie_Sie>haben verbracht</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>度过（时间，假期）</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Er hat einen Monat auf dem Land verbracht und viel erlebt.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V54.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>ablehnen</Stichwort>
	<Einheit>4</Einheit>
	<Anteil>Intentionen</Anteil>
	<Konjugation>
				<Präsen>
					<ich>lehne ab</ich>
					<du>lehnst ab</du>
					<er_sie_es>lehnt ab</er_sie_es>
					<wir>lehnen ab</wir>
					<ihr>lehnt ab</ihr>
					<sie_Sie>lehnen ab</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>lehnte ab</ich>
					<du>lehntest ab</du>
					<er_sie_es>lehnte ab</er_sie_es>
					<wir>lehnten ab</wir>
					<ihr>lehntet ab</ihr>
					<sie_Sie>lehnten ab</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe abgelehnt</ich>
					<du>hast abgelehnt</du>
					<er_sie_es>hat abgelehnt</er_sie_es>
					<wir>haben abgelehnt</wir>
					<ihr>habt abgelehnt</ihr>
					<sie_Sie>haben abgelehnt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>拒绝</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz/>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/server_code_django/mysite/Word_edit/templates/Word_edit/Wort/V98.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>können</Stichwort>
	<Einheit>7</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>kann</ich>
					<du>kannst</du>
					<er_sie_es>kann</er_sie_es>
					<wir>können</wir>
					<ihr>könnt</ihr>
					<sie_Sie>können</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>konnte</ich>
					<du>konntest</du>
					<er_sie_es>konnte</er_sie_es>
					<wir>konnten</wir>
					<ihr>konntet</ihr>
					<sie_Sie>konnten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe gekonnt</ich>
					<du>hast gekonnt</du>
					<er_sie_es>hat gekonnt</er_sie_es>
					<wir>haben gekonnt</wir>
					<ihr>habt gekonnt</ihr>
					<sie_Sie>haben gekonnt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>能够，会，可能</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Was kann ich ihr blop schenken?</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V27.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>fahren</Stichwort>
	<Einheit>3</Einheit>
	<Anteil>Einfürung</Anteil>
	<Konjugation>
				<Präsen>
					<ich/>
					<du/>
					<er_sie_es/>
					<wir/>
					<ihr/>
					<sie_Sie/>
				</Präsen>
				<Präteritum>
					<ich/>
					<du/>
					<er_sie_es/>
					<wir/>
					<ihr/>
					<sie_Sie/>
				</Präteritum>
				<Perfekt hilfsverb="">	
					<ich/>
					<du/>
					<er_sie_es/>
					<wir/>
					<ihr/>
					<sie_Sie/>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>搭，乘，坐（车）；行驶</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Ich fahre gern Rad.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V141.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>fliegen</Stichwort>
	<Einheit>9</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>fliege</ich>
					<du>fliegst</du>
					<er_sie_es>fliegt</er_sie_es>
					<wir>fliegen</wir>
					<ihr>fliegt</ihr>
					<sie_Sie>fliegen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>flog</ich>
					<du>flogst</du>
					<er_sie_es>flog</er_sie_es>
					<wir>flogen</wir>
					<ihr>flogt</ihr>
					<sie_Sie>flogen</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="sein">	
					<ich>bin geflogen</ich>
					<du>bist geflogen</du>
					<er_sie_es>ist geflogen</er_sie_es>
					<wir>sind geflogen</wir>
					<ihr>seid geflogen</ihr>
					<sie_Sie>sind geflogen</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>飞，飞翔</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Er ist ins Ausland geflogen.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>

=== Leidenschaft/Deutsch-Lernen/Wort/V75.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Entry SYSTEM "VerbenModel.dtd"><?xml-stylesheet type="text/xsl" href="VerbRenderTemplate.xslt"?><Entry category="Verben">
	<Stichwort>besichtigen</Stichwort>
	<Einheit>6</Einheit>
	<Anteil>Text</Anteil>
	<Konjugation>
				<Präsen>
					<ich>besichtige</ich>
					<du>besichtigst</du>
					<er_sie_es>besichtigt</er_sie_es>
					<wir>besichtigen</wir>
					<ihr>besichtigt</ihr>
					<sie_Sie>besichtigen</sie_Sie>
				</Präsen>
				<Präteritum>
					<ich>besichtigte</ich>
					<du>besichtigtest</du>
					<er_sie_es>besichtigte</er_sie_es>
					<wir>besichtigten</wir>
					<ihr>besichtigtet</ihr>
					<sie_Sie>besichtigten</sie_Sie>
				</Präteritum>
				<Perfekt hilfsverb="haben">	
					<ich>habe besichtigt</ich>
					<du>hast besichtigt</du>
					<er_sie_es>hat besichtigt</er_sie_es>
					<wir>haben besichtigt</wir>
					<ihr>habt besichtigt</ihr>
					<sie_Sie>haben besichtigt</sie_Sie>
				</Perfekt>
	</Konjugation>
			
			
	<zusammengesetzteWörter>
			<KompositaCollection>
			</KompositaCollection>
			<abgeleiteteWörter>
			</abgeleiteteWörter>
	</zusammengesetzteWörter>
		<Synonymegruppe>
			<Sym/>
		</Synonymegruppe>
		<Antonymegruppe>
			<Anm/>
		</Antonymegruppe>

		<Kollokationen>
		<K/>
		</Kollokationen>
		<AllgemeineErläuterungen>
				<Eintrag transitiv="">
					
					<Chinesisch>参观</Chinesisch>
					<BeispielSammlung>
					<Beispiel>
					<Satz>Er besichtigt eine Mietwohung.</Satz>
					<Übersetzung/>
					</Beispiel>
					</BeispielSammlung>
					
   				</Eintrag>
			</AllgemeineErläuterungen>
	
	
</Entry>
